---
title: "Tidy Data"
output: github_document
---

```{r set up}
library(tidyverse)
```


## `pivor_longer`

Load the PULSE data

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

wide format to long format . . .

```{r}
pulse_data_tidy =
  pulse_data %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "bdi_score_",
    values_to = "bdi"
  )
```

rewrite, combine, and extend (to add a mutate)

```{r}
pulse_data =
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to =  "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
    ) %>%
  relocate(id, visit) %>%
  mutate(visit = recode(visit, "bl" = "00m"))
```


## `pivot_wider`

Make up some data!

```{r}
analysis_result =
  tibble(
    group = c("treatment", "treatment", "placibo", "placibo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
    )

analysis_result %>%
pivot_wider(
  names_from = "time",
  values_from = "mean"
  )
```

